TrainingArguments:
    output_dir: './train_res'
    save_total_limit: 3
    save_steps: 100
    seed: 42

    num_train_epochs: 3
    learning_rate: 0.0001
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16

    weight_decay: 0
    lr_scheduler_type: 'linear'
    gradient_accumulation_steps: 1
    
    warmup_ratio: 0.0
    warmup_steps: 0

    logging_dir: './logs'
    logging_steps: 100

    evaluation_strategy: 'steps'
    eval_steps: 100
    load_best_model_at_end: True

    do_train: True
    do_eval: True
    do_predict: True

    fp16: True
    fp16_opt_level: 'O1'

    label_smoothing_factor: 0.0

    report_to: 'wandb'

    metric_for_best_model: 'rouge1'
    greater_is_better: True



ModelArguments:
    model_name_or_path: 'gogamza/kobart-summarization'
    config_name: 'gogamza/kobart-summarization'
    tokenizer_name: 'gogamza/kobart-summarization'
    cache_dir: ''
    use_fast_tokenizer: True
    model_revision: 'main'  # default
    use_auth_token: False
    resize_position_embeddings: null

DataTrainingArguments:
    dataset_name: 'aihub'     # 데이터셋 이름 summarization_name_mapping에서 사용
    data_file_type: 'json'    
    dataset_config_name: null # TODO: 수정 필요 str
    text_column: null         # TODO: 수정 필요 str
    summary_column: null      # TODO: 수정 필요 str
    train_file: './data/aihub_train.json'       # train data path
    validation_file: './data/aihub_valid.json'  # vaild data path
    test_file: './data/aihub_valid.json'        # test data path

    overwrite_cache: False
    preprocessing_num_workers: null

    max_source_length: 1024   # TODO: 1026인지 확인
    max_target_length: 128

    val_max_target_length: 128
    pad_to_max_length: True

    max_train_samples: null     # TODO: 수정 필요 int
    max_eval_samples: null      # TODO: 수정 필요 int
    max_predict_samples: null   # TODO: 수정 필요 int

    num_beams: 5                # TODO: 수정 필요 int
    ignore_pad_token_for_loss: True
    source_prefix: null         # T5 쓰려면 prefix 설정
    forced_bos_token: null      # TODO: 보고 수정 필요 str